name: Publishing ts-curlconverter

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm install

      - name: Set release information
        run: |
          echo "prerelease=${{ github.event.release.prerelease }}" >> $GITHUB_ENV
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
          if [ "${{ env.prerelease }}" = "true" ]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          else
            echo "AWS_ACCESS_KEY_ID=${{ secrets.APP_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          fi
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Push tree-sitter files into S3 bucket
        run: |
          # Determine the correct S3 bucket based on pre-release status
          if [ "${{ env.prerelease }}" = "true" ]; then
            S3_BUCKET=static-staging.testsigma.com
            
          else
            S3_BUCKET=static.testsigma.com
          fi

          S3_PATH="s3://$S3_BUCKET/ui/ts-curlconverter/${{ env.tag_name }}/"
          echo "S3_PATH=$S3_BUCKET/ui/ts-curlconverter/${{ env.tag_name }}/" >> $GITHUB_ENV

          # Upload files to the determined S3 bucket
          aws s3 cp dist/tree-sitter-bash.wasm $S3_PATH --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --cache-control max-age=315360000
          aws s3 cp node_modules/web-tree-sitter/tree-sitter.wasm $S3_PATH --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --cache-control max-age=315360000

      - name: Replace placeholder with S3 URL
        run: |
          sed -i "s|__S3_PATH__|${{ env.S3_PATH }}|g" src/shell/webParser.ts

      - name: Build the dist 🔧
        run: npm run compile

      - name: Publish package on Github 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}